[phases.setup]
nixPkgs = ["python312", "nodejs_24"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  "/opt/venv/bin/pip install -r requirements.txt",
  "cd frontend/web && rm -rf node_modules package-lock.json && npm install"
]

[phases.build]
cmds = ["cd frontend/web && npm run build"]

[start]
cmd = "/opt/venv/bin/python3 server.py"
